HOST: http://www.hive.org/

--- Hive ---

---
This is the first version!!!
---

--
Players
--

Lists all players for a given application
GET /players
< 200
< Content-Type: application/json
{ 
    "items": [
        { 
            "id": 1,
            "ref": "nx-345",
            "url": "/players/1",
            "name": "Foo Bar",
            "score": 200
        }
] }

Create a new player
POST /players
> Content-Type: application/json
{ 
    "ref": "nx-345",
    "name": "Foo Bar"
}
< 201
< Content-Type: application/json
{ 
    "status": "created", 
    "url": "/players/1"
}

Gets information about a given player
GET /players/:player
< 200
< Content-Type: application/json
{
    "id": 1,
    "ref": "nx-345",
    "url": "/players/1",
    "name": "Foo Bar",
    "score": 200
}

Updates a player
PUT /players/:player
> Content-Type: application/json
{
    "name":"Foo Bar",
    "ref":"nx-456"
}
< 200
< Content-Type: application/json
{
    "status":"updated"
}

Removes a player
DELETE /players/:player
< 200
< Content-Type: application/json
{
    "status": "deleted"
}



