HOST: http://www.hive.org/

--- Hive ---

---
This is the first version!!!
---

--
Players
--

Lists all players for a given application
GET /players
< 200
< Content-Type: application/json
{ 
    "items": [
        { 
            "id": 1,
            "url": "/players/1",
            "name": "Foo Bar"
            "score": 200
        }
] }

Create a new player
POST /players
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }



